sentence = input('Enter your sentence: ')
print(f'Your sentence is : {sentence}')
word1 = input('Enter the word to replace: ')
word2 = input('Enter the word to replace with it: ')
print(sentence.replace(word1, word2))   